/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author hi
 */
public class RGBScreen extends javax.swing.JFrame {

    /**
     * Creates new form RGBScreen
     */
    int R = 0;
    int G = 0;
    int B = 0;
    public RGBScreen() {
        initComponents();
        txtRed.setHorizontalAlignment(JLabel.CENTER);
        txtGreen.setHorizontalAlignment(JLabel.CENTER);
        txtBlue.setHorizontalAlignment(JLabel.CENTER);
        sliderRed.setMaximum(255);
        sliderGreen.setMaximum(255);
        sliderBlue.setMaximum(255);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sliderRed = new javax.swing.JSlider();
        sliderGreen = new javax.swing.JSlider();
        sliderBlue = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        txtRed = new javax.swing.JLabel();
        txtGreen = new javax.swing.JLabel();
        txtBlue = new javax.swing.JLabel();
        colorPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        sliderRed.setValue(0);
        sliderRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderRedStateChanged(evt);
            }
        });
        jPanel1.add(sliderRed);

        sliderGreen.setValue(0);
        sliderGreen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderGreenStateChanged(evt);
            }
        });
        jPanel1.add(sliderGreen);

        sliderBlue.setValue(0);
        sliderBlue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderBlueStateChanged(evt);
            }
        });
        jPanel1.add(sliderBlue);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        txtRed.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtRed.setForeground(new java.awt.Color(255, 0, 0));
        txtRed.setText("R:");
        jPanel2.add(txtRed);

        txtGreen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtGreen.setForeground(new java.awt.Color(0, 159, 0));
        txtGreen.setText("G:");
        jPanel2.add(txtGreen);

        txtBlue.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtBlue.setForeground(new java.awt.Color(0, 0, 255));
        txtBlue.setText("B:");
        jPanel2.add(txtBlue);

        getContentPane().add(jPanel2);

        javax.swing.GroupLayout colorPanelLayout = new javax.swing.GroupLayout(colorPanel);
        colorPanel.setLayout(colorPanelLayout);
        colorPanelLayout.setHorizontalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );
        colorPanelLayout.setVerticalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        getContentPane().add(colorPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderRedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderRedStateChanged
        R = sliderRed.getValue();
        txtRed.setText("R: "+Integer.toString(R));
        changeColer(R, G, B);
    }//GEN-LAST:event_sliderRedStateChanged

    private void sliderGreenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderGreenStateChanged
        G = sliderGreen.getValue();
        txtGreen.setText("G: "+Integer.toString(G));
        changeColer(R, G, B);
    }//GEN-LAST:event_sliderGreenStateChanged

    private void sliderBlueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderBlueStateChanged
        B = sliderBlue.getValue();
        txtBlue.setText("B: "+Integer.toString(B));
        changeColer(R, G, B);       
    }//GEN-LAST:event_sliderBlueStateChanged
    
    public void changeColer(int R, int G,int B){
        Color c = new Color(R, G, B);
        colorPanel.setBackground(c);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RGBScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RGBScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RGBScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RGBScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RGBScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel colorPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider sliderBlue;
    private javax.swing.JSlider sliderGreen;
    private javax.swing.JSlider sliderRed;
    private javax.swing.JLabel txtBlue;
    private javax.swing.JLabel txtGreen;
    private javax.swing.JLabel txtRed;
    // End of variables declaration//GEN-END:variables
}
