/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;


/**
 *
 * @author hi
 */
public class MangHinh extends javax.swing.JFrame {

    /**
     * Creates new form MangHinh
     */
    
    //fields cho imageIcon
    ImageIcon icon1 = new ImageIcon("img/img1.jpg");
    ImageIcon icon2 = new ImageIcon("img/img2.jpg");
    ImageIcon icon3 = new ImageIcon("img/img3.jpg");
    ImageIcon icon4 = new ImageIcon("img/img4.jpg");
    ImageIcon icon5 = new ImageIcon("img/img5.jpg");
    ImageIcon iconDefault = new ImageIcon("img/default.png");
    ImageIcon currentIcon;
    //Hoi thay lai cho này
    //Icon và ImageIcon theo chức năng thì nó khác ra sao???
    //Icon icon6 = new ImageIcon("img/img1.jpg");
    
    public MangHinh() {
        initComponents();
        this.setResizable(true);
        //Buoc 1 cho hinh vao cac button dung function không nên lặp
        rescaleImageForButtons(btn1, icon1);
        rescaleImageForButtons(btn2, icon2);
        rescaleImageForButtons(btn3, icon3);
        rescaleImageForButtons(btn4, icon4);
        rescaleImageForButtons(btn5, icon5);
        rescaleImageForLabel(imgLabel, iconDefault);
        
    }
    
    //buoc 2 la fuction scaling
    final void rescaleImageForButtons(JButton btnX, ImageIcon ic){
//        Image iToI = ic.getImage();
//        Image rescaleImage = iToI.getScaledInstance(btnX.getWidth(), btnX.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon iconRescaled = new ImageIcon(rescaleImage);
        Image iToI2 = ic.getImage().getScaledInstance(btnX.getWidth(), btnX.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon iconRescaled = new ImageIcon(iToI2);
        btnX.setIcon(iconRescaled);
    }
    
    final void rescaleImageForLabel(JLabel lb, ImageIcon ic){
//        Image iToI = ic.getImage();
//        Image rescaleImage = iToI.getScaledInstance(imgLabel.getWidth(), imgLabel.getHeight(), Image.SCALE_SMOOTH);
        Image iToI2 = ic.getImage().getScaledInstance(imgLabel.getWidth(), imgLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon iconRescaled = new ImageIcon(iToI2);
        lb.setIcon(iconRescaled);    
    }

//    @Override
//    public void paint(Graphics g) {
//        super.paint(g); //To change body of generated methods, choose Tools | Templates.
//        rescaleImageForLabel(imgLabel, icon1);
//        rescaleImageForLabel(imgLabel, icon2);
//        rescaleImageForLabel(imgLabel, icon3);
//        rescaleImageForLabel(imgLabel, icon4);
//        rescaleImageForLabel(imgLabel, icon5);
//    }
    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        if(currentIcon != null){
            rescaleImageForLabel(imgLabel, currentIcon);
        }
        
    
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgLabel = new javax.swing.JLabel();
        btnPanel = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 505));
        getContentPane().add(imgLabel, java.awt.BorderLayout.CENTER);

        btn1.setPreferredSize(new java.awt.Dimension(100, 100));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        btnPanel.add(btn1);

        btn2.setPreferredSize(new java.awt.Dimension(100, 100));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        btnPanel.add(btn2);

        btn3.setPreferredSize(new java.awt.Dimension(100, 100));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        btnPanel.add(btn3);

        btn4.setPreferredSize(new java.awt.Dimension(100, 100));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        btnPanel.add(btn4);

        btn5.setPreferredSize(new java.awt.Dimension(100, 100));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        btnPanel.add(btn5);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btnPanel.add(jLayeredPane1);

        getContentPane().add(btnPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // buoc 3 button action
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        rescaleImageForLabel(imgLabel, icon1);
        currentIcon = new ImageIcon("img/img1.jpg");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        rescaleImageForLabel(imgLabel, icon2);
        currentIcon = new ImageIcon("img/img2.jpg");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        rescaleImageForLabel(imgLabel, icon3);
        currentIcon = new ImageIcon("img/img3.jpg");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        rescaleImageForLabel(imgLabel, icon4);
        currentIcon = new ImageIcon("img/img4.jpg");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        rescaleImageForLabel(imgLabel, icon5);
        currentIcon = new ImageIcon("img/img5.jpg");
    }//GEN-LAST:event_btn5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MangHinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MangHinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MangHinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MangHinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MangHinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
