/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author hi
 */
public class Screen2 extends javax.swing.JFrame {

    /**
     * Creates new form Screen2
     */
    
    ImageIcon icon1 = new ImageIcon("img/img1.jpg");
    ImageIcon icon2 = new ImageIcon("img/img2.jpg");
    ImageIcon icon3 = new ImageIcon("img/img3.jpg");
    ImageIcon icon4 = new ImageIcon("img/img4.jpg");
    ImageIcon icon5 = new ImageIcon("img/img5.jpg");
    ImageIcon iconDefault = new ImageIcon("img/default.png");
    ImageIcon currentIcon;
    public Screen2() {
        initComponents();       
        rescaleImageForLabel(lb, iconDefault);
        this.setSize(900, 900);
        currentIcon = iconDefault;
    }
    final void rescaleImageForLabel(JLabel lb, ImageIcon ic){

        Image iToI2 = ic.getImage().getScaledInstance(lb.getWidth() - 10, lb.getHeight() - 10, Image.SCALE_SMOOTH);
        ImageIcon iconRescaled = new ImageIcon(iToI2);
        lb.setIcon(iconRescaled);    
    }  
    
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        if(currentIcon != null){
            rescaleImageForLabel(lb, currentIcon);
        }
        
    
    }      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb = new javax.swing.JLabel();
        box = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(lb, java.awt.BorderLayout.CENTER);

        box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Red", "Stuff", "City", "Beach" }));
        box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxActionPerformed(evt);
            }
        });
        getContentPane().add(box, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxActionPerformed
       int x = box.getSelectedIndex();
        switch(x){
            case 0:
                rescaleImageForLabel(lb, icon1);
                currentIcon = icon1;
                break;
            case 1:
                rescaleImageForLabel(lb, icon2);
                currentIcon = icon2;
                break;
            case 2:
                rescaleImageForLabel(lb, icon3);
                currentIcon = icon3;
                break;
            case 3:
                rescaleImageForLabel(lb, icon4);
                currentIcon = icon4;
                break;    
            case 4:
                rescaleImageForLabel(lb, icon5);
                currentIcon = icon5;
                break;    
                
                
        }
    }//GEN-LAST:event_boxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box;
    private javax.swing.JLabel lb;
    // End of variables declaration//GEN-END:variables
}
