/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author hi
 */
public class Screen1 extends javax.swing.JFrame {

    /**
     * Creates new form Screen1
     */
    
    ImageIcon icon1 = new ImageIcon("img/img1.jpg");
    ImageIcon icon2 = new ImageIcon("img/img2.jpg");
    ImageIcon icon3 = new ImageIcon("img/img3.jpg");
    ImageIcon icon4 = new ImageIcon("img/img4.jpg");
    ImageIcon icon5 = new ImageIcon("img/img5.jpg");
    ImageIcon iconDefault = new ImageIcon("img/default.png");
    ImageIcon currentIcon;
    
    public Screen1() {
        initComponents();
        this.setSize(900, 900);
        rescaleImageForLabel(lb, iconDefault);
        currentIcon = iconDefault;
        
    }
    final void rescaleImageForLabel(JLabel lb, ImageIcon ic){

        Image iToI2 = ic.getImage().getScaledInstance(lb.getWidth() - 10, lb.getHeight() - 10, Image.SCALE_SMOOTH);
        ImageIcon iconRescaled = new ImageIcon(iToI2);
        lb.setIcon(iconRescaled);    
    }
    
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        if(currentIcon != null){
            rescaleImageForLabel(lb, currentIcon);
        }
        
    
    }      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listBox = new javax.swing.JList<>();
        lb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listBox.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Blue", "Red", "Stuff", "City", "Beach" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listBox.setMinimumSize(new java.awt.Dimension(90, 110));
        listBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listBoxMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listBox);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.LINE_START);
        getContentPane().add(lb, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listBoxMouseClicked
        int x = listBox.getSelectedIndex();
        switch(x){
            case 0:
                rescaleImageForLabel(lb, icon1);
                currentIcon = icon1;
                break;
            case 1:
                rescaleImageForLabel(lb, icon2);
                currentIcon = icon2;
                break;
            case 2:
                rescaleImageForLabel(lb, icon3);
                currentIcon = icon3;
                break;
            case 3:
                rescaleImageForLabel(lb, icon4);
                currentIcon = icon4;
                break;    
            case 4:
                rescaleImageForLabel(lb, icon5);
                currentIcon = icon5;
                break;    
                
                
        }
    }//GEN-LAST:event_listBoxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb;
    private javax.swing.JList<String> listBox;
    // End of variables declaration//GEN-END:variables
}
